//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub mod prelude;

pub mod asset;
pub mod asset_type;
pub mod contact;
pub mod contact_type;
pub mod current_sheet;
pub mod expense;
pub mod expense_type;
pub mod gender;
pub mod transaction;
pub mod transaction_type;
pub mod user;
pub mod user_contact;
pub mod user_role;
