//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Binary(16)")]
    pub id: Vec<u8>,
    #[sea_orm(unique)]
    pub username: String,
    pub password: String,
    #[sea_orm(unique)]
    pub email: String,
    pub first_name: String,
    pub last_name: String,
    #[sea_orm(unique)]
    pub mcp_token: String,
    #[sea_orm(column_type = "Binary(16)")]
    pub gender_id: Vec<u8>,
    #[sea_orm(column_type = "Binary(16)")]
    pub user_role_id: Vec<u8>,
    pub created_at: Option<DateTimeUtc>,
    pub updated_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::asset::Entity")]
    Asset,
    #[sea_orm(has_many = "super::asset_type::Entity")]
    AssetType,
    #[sea_orm(has_many = "super::contact_type::Entity")]
    ContactType,
    #[sea_orm(has_many = "super::current_sheet::Entity")]
    CurrentSheet,
    #[sea_orm(has_many = "super::expense::Entity")]
    Expense,
    #[sea_orm(has_many = "super::expense_type::Entity")]
    ExpenseType,
    #[sea_orm(
        belongs_to = "super::gender::Entity",
        from = "Column::GenderId",
        to = "super::gender::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    Gender,
    #[sea_orm(has_many = "super::transaction::Entity")]
    Transaction,
    #[sea_orm(has_many = "super::user_contact::Entity")]
    UserContact,
    #[sea_orm(
        belongs_to = "super::user_role::Entity",
        from = "Column::UserRoleId",
        to = "super::user_role::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    UserRole,
}

impl Related<super::asset::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Asset.def()
    }
}

impl Related<super::asset_type::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AssetType.def()
    }
}

impl Related<super::contact_type::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ContactType.def()
    }
}

impl Related<super::current_sheet::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CurrentSheet.def()
    }
}

impl Related<super::expense::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Expense.def()
    }
}

impl Related<super::expense_type::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ExpenseType.def()
    }
}

impl Related<super::gender::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Gender.def()
    }
}

impl Related<super::transaction::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Transaction.def()
    }
}

impl Related<super::user_contact::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserContact.def()
    }
}

impl Related<super::user_role::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserRole.def()
    }
}

impl Related<super::contact::Entity> for Entity {
    fn to() -> RelationDef {
        super::user_contact::Relation::Contact.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::user_contact::Relation::User.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
